# Generated by Django 3.1.6 on 2021-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rated_overall',
            field=models.IntegerField(default=0),
        ),
    ]
